
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kleivy Gomes
 */
public class TabelaDeAlunos extends javax.swing.JFrame {

    /**
     * Creates new form TabelaDeAlunos
     */
    public TabelaDeAlunos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        alunos = new javax.swing.JScrollPane();
        Talunos = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Registar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        alunos.setBorder(null);

        Talunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Nome", "Curso", "Ano", "Matricula", "Bolsa", "CVE", "SET", "OUT", "NOV", "DEZ", "JAN", "MAR", "ABR", "MAI", "JUN", "JUL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Talunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TalunosMouseClicked(evt);
            }
        });
        alunos.setViewportView(Talunos);
        if (Talunos.getColumnModel().getColumnCount() > 0) {
            Talunos.getColumnModel().getColumn(4).setResizable(false);
            Talunos.getColumnModel().getColumn(5).setResizable(false);
            Talunos.getColumnModel().getColumn(7).setResizable(false);
            Talunos.getColumnModel().getColumn(8).setResizable(false);
            Talunos.getColumnModel().getColumn(9).setResizable(false);
            Talunos.getColumnModel().getColumn(10).setResizable(false);
            Talunos.getColumnModel().getColumn(11).setResizable(false);
            Talunos.getColumnModel().getColumn(12).setResizable(false);
            Talunos.getColumnModel().getColumn(13).setResizable(false);
            Talunos.getColumnModel().getColumn(14).setResizable(false);
            Talunos.getColumnModel().getColumn(15).setResizable(false);
            Talunos.getColumnModel().getColumn(16).setResizable(false);
        }

        jScrollPane4.setViewportView(alunos);

        jButton3.setText("Pagamento");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Apagar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Registo r = new Registo(this,true);
        r.setVisible(true);

        DefaultTableModel dtm = (DefaultTableModel) Talunos.getModel();
        Object[] dados = {r.numaluno,r.nomealuno,r.Acurso,r.Aescolaridade,r.Amatricula,r.abolsa,r.amontante,false,false,false,false,false,false,false,false,false,false};
        dtm.addRow(dados);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        if(Talunos.getSelectedRow() != -1){
            Pagamento p = new Pagamento(this,true);
            p.setVisible(true);;
            DefaultTableModel dtm = (DefaultTableModel) Talunos.getModel();
            if(p.tipodepagamento.equals("mes")){
                if(p.semestreapagar.equals("1º Semestre")){
                    if(p.mesapagar.equals("Setembro")){
                        Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 7);
                    }
                    if(p.mesapagar.equals("Outubro")){
                        Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 8);
                    }
                    if(p.mesapagar.equals("Novembro")){
                        Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 9);
                    }
                    if(p.mesapagar.equals("Dezembro")){
                        Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 10);
                    }
                    if(p.mesapagar.equals("Janeiro")){
                        Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 11);
                    }
                
                
                }else{
                    if(p.semestreapagar.equals("2º Semestre")){
                        if(p.mesapagar.equals("Março")){
                            Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 12);
                        }
                        if(p.mesapagar.equals("Abril")){
                            Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 13);
                        }
                        if(p.mesapagar.equals("Maio")){
                            Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 14);
                        }
                        if(p.mesapagar.equals("Junho")){
                            Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 15);
                        }
                        if(p.mesapagar.equals("Julho")){
                            Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 16);
                        }
                    }
                }
                
                
            }else{
                if(p.tipodepagamento.equals("semestre")){
                    if(p.semestreapagar.equals("1º Semestre")){
                        Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 7);
                        Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 8);
                        Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 9);
                        Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 10);
                        Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 11);
                    
                    }else{
                        Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 12);
                        Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 13);
                        Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 14);
                        Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 15);
                        Talunos.setValueAt(p.pagarmes, Talunos.getSelectedRow(), 16);
                    }
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione aluno para efetuar pagamentto");
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TalunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TalunosMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_TalunosMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(Talunos.getSelectedRow() != -1){
           DefaultTableModel dtm = (DefaultTableModel) Talunos.getModel();
           dtm.removeRow(Talunos.getSelectedRow());
            
        }else{
            JOptionPane.showMessageDialog(null, "ERRO: Selecione aluno para remover");
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaDeAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaDeAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaDeAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaDeAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaDeAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Talunos;
    private javax.swing.JScrollPane alunos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
